// Auto-generated by generate-types.js — do not edit manually
// Re-run 'yarn generate:types' to update

export type { components, operations, paths } from './models';
import type { components } from './models';

// ============= UTILITY TYPES =============
// Pydantic Optional[X] serializes as X | null, but frontend uses undefined.
// Use DeNull<T> to convert null -> undefined for local state.
export type DeNull<T> = T extends null ? undefined : T extends object ? { [K in keyof T]: DeNull<T[K]> } : T;

// ============= ENUMS =============

// ============= MODELS =============
export type ActiveJobResponse = components['schemas']['ActiveJobResponse'];
export type BodyPart = components['schemas']['BodyPart'];
export type ConversationListResponse = components['schemas']['ConversationListResponse'];
export type ExerciseCategory = components['schemas']['ExerciseCategory'];
export type ExerciseCreate = components['schemas']['ExerciseCreate'];
export type ExerciseHistoryEntry = components['schemas']['ExerciseHistoryEntry'];
export type ExerciseHistoryResponse = components['schemas']['ExerciseHistoryResponse'];
export type ExerciseHistorySet = components['schemas']['ExerciseHistorySet'];
export type ExerciseKind = components['schemas']['ExerciseKind'];
export type ExerciseUpdate = components['schemas']['ExerciseUpdate'];
export type HTTPValidationError = components['schemas']['HTTPValidationError'];
export type InsightsResponse = components['schemas']['InsightsResponse'];
export type Job = components['schemas']['Job'];
export type MessageResponse = components['schemas']['MessageResponse'];
export type MessagesResponse = components['schemas']['MessagesResponse'];
export type MuscleLoad = components['schemas']['MuscleLoad'];
export type MuscleTopExercise = components['schemas']['MuscleTopExercise'];
export type MuscleVolumeEntry = components['schemas']['MuscleVolumeEntry'];
export type MuscleVolumeResponse = components['schemas']['MuscleVolumeResponse'];
export type PRType = components['schemas']['PRType'];
export type PlannedWorkoutCreate = components['schemas']['PlannedWorkoutCreate'];
export type PlannedWorkoutStatus = components['schemas']['PlannedWorkoutStatus'];
export type PlannedWorkoutType = components['schemas']['PlannedWorkoutType'];
export type PlannedWorkoutUpdate = components['schemas']['PlannedWorkoutUpdate'];
export type ProfileInsights = components['schemas']['ProfileInsights'];
export type ProfileUpdate = components['schemas']['ProfileUpdate'];
export type RecurrenceType = components['schemas']['RecurrenceType'];
export type SetType = components['schemas']['SetType'];
export type Sex = components['schemas']['Sex'];
export type StartChatResponse = components['schemas']['StartChatResponse'];
export type TemplateExerciseItem = components['schemas']['TemplateExerciseItem'];
export type TemplateSetItem = components['schemas']['TemplateSetItem'];
export type TrainingAge = components['schemas']['TrainingAge'];
export type TrainingPhase = components['schemas']['TrainingPhase'];
export type UserContext = components['schemas']['UserContext'];
export type UserCreate = components['schemas']['UserCreate'];
export type UserLogin = components['schemas']['UserLogin'];
export type UserProfile = components['schemas']['UserProfile'];
export type ValidationError = components['schemas']['ValidationError'];
export type WorkoutCountResponse = components['schemas']['WorkoutCountResponse'];
export type WorkoutExerciseItem = components['schemas']['WorkoutExerciseItem'];
export type WorkoutExerciseSummary = components['schemas']['WorkoutExerciseSummary'];
export type WorkoutSessionCreate = components['schemas']['WorkoutSessionCreate'];
export type WorkoutSessionUpdate = components['schemas']['WorkoutSessionUpdate'];
export type WorkoutSetItem = components['schemas']['WorkoutSetItem'];
export type WorkoutSummary = components['schemas']['WorkoutSummary'];
export type WorkoutTemplateCreate = components['schemas']['WorkoutTemplateCreate'];

// ============= ALIASES =============
export type UserResponse = components['schemas']['UserResponse'];
export type User = UserResponse;
export type ExerciseResponse = components['schemas']['ExerciseResponse'];
export type Exercise = ExerciseResponse;
export type WorkoutSessionResponse = components['schemas']['WorkoutSessionResponse'];
export type WorkoutSession = WorkoutSessionResponse;
export type WorkoutTemplateResponse = components['schemas']['WorkoutTemplateResponse'];
export type WorkoutTemplate = WorkoutTemplateResponse;
export type PlannedWorkoutResponse = components['schemas']['PlannedWorkoutResponse'];
export type PlannedWorkout = PlannedWorkoutResponse;
export type PRRecordResponse = components['schemas']['PRRecordResponse'];
export type PRRecord = PRRecordResponse;
export type WorkoutSet = WorkoutSetItem;
export type TemplateSet = TemplateSetItem;
export type WorkoutExercise = WorkoutExerciseItem;
export type TemplateExercise = TemplateExerciseItem;
export type ExerciseHistory = ExerciseHistoryEntry;
export type Conversation = components['schemas']['Conversation'];
