/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apple Signin
         * @description Verify Apple's identity token (JWT) using Apple's JWKS,
         *     find or create a user (store `apple_sub` on user document),
         *     and return our app access token.
         *     Expects payload: { apple_token: str, client_id?: str, email?: str }
         */
        post: operations["apple_signin_api_auth_apple_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversations */
        get: operations["get_conversations_api_ai_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/conversations/{conversation_id}/active-job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Job */
        get: operations["get_active_job_api_ai_conversations__conversation_id__active_job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chat/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Ai Chat */
        post: operations["start_ai_chat_api_ai_chat_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_api_ai_conversations__conversation_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Get user profile
         */
        get: operations["get_profile_api_profile_get"];
        /**
         * Update Profile
         * @description Update user profile and auto-generate insights
         */
        put: operations["update_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Context
         * @description Get aggregated user context for AI and UI logic
         */
        get: operations["get_user_context_api_profile_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/insights/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Insights
         * @description Generate AI-powered insights from user's profile
         */
        post: operations["generate_insights_api_profile_insights_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercises */
        get: operations["get_exercises_api_exercises_get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_exercises_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Exercise */
        get: operations["get_exercise_api_exercises__exercise_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Exercise */
        patch: operations["update_exercise_api_exercises__exercise_id__patch"];
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Templates */
        get: operations["get_templates_api_templates_get"];
        put?: never;
        /** Create Template */
        post: operations["create_template_api_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Template */
        get: operations["get_template_api_templates__template_id__get"];
        /** Update Template */
        put: operations["update_template_api_templates__template_id__put"];
        post?: never;
        /** Delete Template */
        delete: operations["delete_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workouts */
        get: operations["get_workouts_api_workouts_get"];
        put?: never;
        /** Start Workout */
        post: operations["start_workout_api_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout */
        get: operations["get_workout_api_workouts__workout_id__get"];
        /** Update Workout */
        put: operations["update_workout_api_workouts__workout_id__put"];
        post?: never;
        /**
         * Delete Workout
         * @description Delete a workout session
         */
        delete: operations["delete_workout_api_workouts__workout_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout Count All */
        get: operations["get_workout_count_all_api_workouts_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/history/by-exercise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workout History By Exercise
         * @description Return FULL workout history for a specific exercise,
         *     grouped by workout, preserving sets and workout metadata.
         */
        get: operations["get_workout_history_by_exercise_api_workouts_history_by_exercise_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/by-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workouts By Date */
        get: operations["get_workouts_by_date_api_workouts_by_date_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/by-date-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workouts By Date Range */
        get: operations["get_workouts_by_date_range_api_workouts_by_date_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/batch/{workout_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workouts Batch */
        get: operations["get_workouts_batch_api_workouts_batch__workout_ids__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{workout_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workout Detail
         * @description Get detailed workout summary with exercise breakdown
         */
        get: operations["get_workout_detail_api_workouts__workout_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prs */
        get: operations["get_prs_api_prs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Planned Workouts
         * @description Get planned workouts for a user, including unscheduled workouts that happened on the date.
         *     - If 'date' is provided, returns workouts for that specific day (expanded if recurring + actual sessions)
         *     - If 'start_date' and 'end_date' are provided, returns workouts in that range (expanded + actual sessions)
         *     - Otherwise, returns all planned workouts (not expanded)
         */
        get: operations["get_planned_workouts_api_planned_workouts_get"];
        put?: never;
        /**
         * Create Planned Workout
         * @description Create a new planned workout (one-time or recurring)
         */
        post: operations["create_planned_workout_api_planned_workouts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Planned Workout
         * @description Get a specific planned workout
         */
        get: operations["get_planned_workout_api_planned_workouts__workout_id__get"];
        /**
         * Update Planned Workout
         * @description Update a planned workout
         */
        put: operations["update_planned_workout_api_planned_workouts__workout_id__put"];
        post?: never;
        /**
         * Delete Planned Workout
         * @description Delete a planned workout
         */
        delete: operations["delete_planned_workout_api_planned_workouts__workout_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root_api__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveJobResponse */
        ActiveJobResponse: {
            job?: components["schemas"]["Job"] | null;
        };
        /**
         * BodyPart
         * @enum {string}
         */
        BodyPart: "Chest" | "Back" | "Shoulders" | "Biceps" | "Triceps" | "Forearms" | "Core" | "Abs" | "Obliques" | "Legs" | "Quads" | "Hamstrings" | "Glutes" | "Glute Medius" | "Calves" | "Hips" | "Traps" | "Full Body" | "Feet" | "Ankles" | "Shins" | "Other";
        /** Conversation */
        Conversation: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Last Message At
             * Format: date-time
             */
            last_message_at: string;
            /** Active Job Id */
            active_job_id?: string | null;
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["Conversation"][];
        };
        /**
         * ExerciseCategory
         * @enum {string}
         */
        ExerciseCategory: "Strength" | "Cardio" | "Mobility" | "Plyometric" | "Isometric Strength" | "Stability" | "Recovery" | "Control";
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Name */
            name: string;
            exercise_kind: components["schemas"]["ExerciseKind"];
            /** Primary Body Parts */
            primary_body_parts: components["schemas"]["BodyPart"][];
            /**
             * Secondary Body Parts
             * @default []
             */
            secondary_body_parts: components["schemas"]["BodyPart"][];
            /** @default Strength */
            category: components["schemas"]["ExerciseCategory"];
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
            /** Instructions */
            instructions?: string | null;
            /** Image */
            image?: string | null;
        };
        /** ExerciseHistoryEntry */
        ExerciseHistoryEntry: {
            /** Workout Id */
            workout_id: string;
            /** Workout Name */
            workout_name: string;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["ExerciseHistorySet"][];
        };
        /** ExerciseHistoryResponse */
        ExerciseHistoryResponse: {
            /** Exercise Id */
            exercise_id: string;
            exercise_kind: components["schemas"]["ExerciseKind"];
            /** Window Days */
            window_days: number;
            /** Workouts Scanned */
            workouts_scanned: number;
            /** History */
            history: components["schemas"]["ExerciseHistoryEntry"][];
            /** Max Weight */
            max_weight?: number | null;
            /** Max Reps */
            max_reps?: number | null;
            /** Best E1Rm */
            best_e1rm?: number | null;
        };
        /** ExerciseHistorySet */
        ExerciseHistorySet: {
            /** Reps */
            reps?: number | null;
            /** Weight */
            weight?: number | null;
            /** Duration */
            duration?: number | null;
            /** Distance */
            distance?: number | null;
            /** @default normal */
            set_type: components["schemas"]["SetType"];
            /** Rest Timer */
            rest_timer?: number | null;
        };
        /**
         * ExerciseKind
         * @enum {string}
         */
        ExerciseKind: "Barbell" | "Dumbbell" | "Machine/Other" | "Weighted Bodyweight" | "Assisted Bodyweight" | "Reps Only" | "Duration" | "Cardio" | "Weighted Cardio" | "Weighted Duration" | "Band" | "Cable" | "Kettlebell" | "EMOM (Every Minute On The Minute)" | "ETOT (Every Thirty Seconds on Thirty Seconds)";
        /** ExerciseResponse */
        ExerciseResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            exercise_kind: components["schemas"]["ExerciseKind"];
            /** Primary Body Parts */
            primary_body_parts: components["schemas"]["BodyPart"][];
            /**
             * Secondary Body Parts
             * @default []
             */
            secondary_body_parts: components["schemas"]["BodyPart"][];
            /** @default Strength */
            category: components["schemas"]["ExerciseCategory"];
            /**
             * Is Custom
             * @default false
             */
            is_custom: boolean;
            /** User Id */
            user_id?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Image */
            image?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ExerciseUpdate */
        ExerciseUpdate: {
            /** Instructions */
            instructions?: string | null;
            /** Image */
            image?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Insights */
            insights: {
                [key: string]: unknown;
            };
        };
        /** Job */
        Job: {
            /** Id */
            _id: string;
            /** Status */
            status: string;
            /** Kind */
            kind: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MessagesResponse */
        MessagesResponse: {
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
        };
        /** PRRecordResponse */
        PRRecordResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Exercise Id */
            exercise_id: string;
            /** Workout Id */
            workout_id?: string | null;
            /** @default 1rm */
            pr_type: components["schemas"]["PRType"];
            /** Weight */
            weight?: number | null;
            /** Reps */
            reps?: number | null;
            /** Duration */
            duration?: number | null;
            /** Volume */
            volume?: number | null;
            /** Estimated 1Rm */
            estimated_1rm?: number | null;
            /**
             * Date
             * Format: date-time
             */
            date?: string;
        };
        /**
         * PRType
         * @enum {string}
         */
        PRType: "1rm" | "weight" | "reps" | "volume" | "duration";
        /**
         * PlannedWorkoutCreate
         * @description Create a planned workout
         */
        PlannedWorkoutCreate: {
            /** Date */
            date: string;
            /** Name */
            name: string;
            /** Template Id */
            template_id?: string | null;
            type?: components["schemas"]["PlannedWorkoutType"] | null;
            /** Notes */
            notes?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /** Inline Exercises */
            inline_exercises?: components["schemas"]["TemplateExerciseItem"][] | null;
            /**
             * Is Recurring
             * @default false
             */
            is_recurring: boolean;
            recurrence_type?: components["schemas"]["RecurrenceType"] | null;
            /** Recurrence Days */
            recurrence_days?: number[] | null;
            /** Recurrence End Date */
            recurrence_end_date?: string | null;
        };
        /** PlannedWorkoutResponse */
        PlannedWorkoutResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Date */
            date: string;
            /** Name */
            name: string;
            /** Template Id */
            template_id?: string | null;
            /** Inline Exercises */
            inline_exercises?: components["schemas"]["TemplateExerciseItem"][] | null;
            type?: components["schemas"]["PlannedWorkoutType"] | null;
            /** Notes */
            notes?: string | null;
            /** @default planned */
            status: components["schemas"]["PlannedWorkoutStatus"];
            /** Workout Session Id */
            workout_session_id?: string | null;
            /**
             * Order
             * @default 0
             */
            order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Is Recurring
             * @default false
             */
            is_recurring: boolean;
            recurrence_type?: components["schemas"]["RecurrenceType"] | null;
            /** Recurrence Days */
            recurrence_days?: number[] | null;
            /** Recurrence End Date */
            recurrence_end_date?: string | null;
            /** Recurrence Parent Id */
            recurrence_parent_id?: string | null;
            /**
             * Is Override
             * @default false
             */
            is_override: boolean;
            /** Original Date */
            original_date?: string | null;
        };
        /**
         * PlannedWorkoutStatus
         * @enum {string}
         */
        PlannedWorkoutStatus: "planned" | "in_progress" | "completed" | "skipped";
        /**
         * PlannedWorkoutType
         * @enum {string}
         */
        PlannedWorkoutType: "strength" | "run" | "mobility" | "cardio" | "hiit" | "other";
        /**
         * PlannedWorkoutUpdate
         * @description Update a planned workout
         */
        PlannedWorkoutUpdate: {
            /** Date */
            date?: string | null;
            /** Name */
            name?: string | null;
            /** Template Id */
            template_id?: string | null;
            type?: components["schemas"]["PlannedWorkoutType"] | null;
            /** Notes */
            notes?: string | null;
            /** Order */
            order?: number | null;
            status?: components["schemas"]["PlannedWorkoutStatus"] | null;
            /** Inline Exercises */
            inline_exercises?: components["schemas"]["TemplateExerciseItem"][] | null;
            /** Is Recurring */
            is_recurring?: boolean | null;
            recurrence_type?: components["schemas"]["RecurrenceType"] | null;
            /** Recurrence Days */
            recurrence_days?: number[] | null;
            /** Recurrence End Date */
            recurrence_end_date?: string | null;
        };
        /**
         * ProfileInsights
         * @description AI-generated insights from user's freeform profile text
         */
        ProfileInsights: {
            /**
             * Injury Tags
             * @default []
             */
            injury_tags: string[];
            /**
             * Current Issues
             * @default []
             */
            current_issues: string[];
            /**
             * Strength Tags
             * @default []
             */
            strength_tags: string[];
            /**
             * Weak Point Tags
             * @default []
             */
            weak_point_tags: string[];
            /**
             * Training Phases
             * @default []
             */
            training_phases: components["schemas"]["TrainingPhase"][];
            /** Psych Profile */
            psych_profile?: string | null;
        };
        /**
         * ProfileUpdate
         * @description Update user profile
         */
        ProfileUpdate: {
            sex?: components["schemas"]["Sex"] | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            training_age?: components["schemas"]["TrainingAge"] | null;
            /** Goals */
            goals?: string | null;
            /** Injury History */
            injury_history?: string | null;
            /** Weaknesses */
            weaknesses?: string | null;
            /** Strengths */
            strengths?: string | null;
            /** Background Story */
            background_story?: string | null;
        };
        /**
         * RecurrenceType
         * @enum {string}
         */
        RecurrenceType: "daily" | "weekly" | "monthly";
        /**
         * SetType
         * @enum {string}
         */
        SetType: "normal" | "warmup" | "cooldown" | "failure";
        /**
         * Sex
         * @enum {string}
         */
        Sex: "male" | "female" | "other";
        /** StartChatResponse */
        StartChatResponse: {
            /** Job Id */
            job_id: string;
            /** Conversation Id */
            conversation_id: string;
        };
        /** TemplateExerciseItem */
        TemplateExerciseItem: {
            /** Exercise Id */
            exercise_id: string;
            /** Order */
            order: number;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["TemplateSetItem"][];
            /** Notes */
            notes?: string | null;
            /**
             * Default Sets
             * @default 3
             */
            default_sets: number;
            /**
             * Default Reps
             * @default 10
             */
            default_reps: number | null;
            /** Default Weight */
            default_weight?: number | null;
            /** Default Duration */
            default_duration?: number | null;
            /** Default Distance */
            default_distance?: number | null;
        };
        /**
         * TemplateSetItem
         * @description A single set in a template exercise with default values
         */
        TemplateSetItem: {
            /** Weight */
            weight?: number | null;
            /** Reps */
            reps?: number | null;
            /** Duration */
            duration?: number | null;
            /** Distance */
            distance?: number | null;
            /** @default normal */
            set_type: components["schemas"]["SetType"];
            /** Rest Timer */
            rest_timer?: number | null;
        };
        /**
         * TrainingAge
         * @enum {string}
         */
        TrainingAge: "new" | "1-2y" | "2-5y" | "5y+";
        /**
         * TrainingPhase
         * @description A phase in the user's training history
         */
        TrainingPhase: {
            /** Label */
            label: string;
            /** Description */
            description: string;
        };
        /**
         * UserContext
         * @description Aggregated user context for AI and UI logic
         */
        UserContext: {
            /**
             * Basic Info
             * @default {}
             */
            basic_info: {
                [key: string]: unknown;
            };
            /**
             * Training Context
             * @default {}
             */
            training_context: {
                [key: string]: unknown;
            };
            /**
             * Physiology
             * @default {}
             */
            physiology: {
                [key: string]: unknown;
            };
            /** Background Story */
            background_story?: string | null;
            /**
             * Is Profile Complete
             * @default false
             */
            is_profile_complete: boolean;
            insights?: components["schemas"]["ProfileInsights"] | null;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserProfile
         * @description User profile information
         */
        UserProfile: {
            sex?: components["schemas"]["Sex"] | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            training_age?: components["schemas"]["TrainingAge"] | null;
            /** Goals */
            goals?: string | null;
            /** Injury History */
            injury_history?: string | null;
            /** Weaknesses */
            weaknesses?: string | null;
            /** Strengths */
            strengths?: string | null;
            /** Background Story */
            background_story?: string | null;
            insights?: components["schemas"]["ProfileInsights"] | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Token */
            token: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkoutCountResponse */
        WorkoutCountResponse: {
            /** Count */
            count: number;
        };
        /** WorkoutExerciseItem */
        WorkoutExerciseItem: {
            /** Exercise Id */
            exercise_id: string;
            /** Order */
            order: number;
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["WorkoutSetItem"][];
            /** Notes */
            notes?: string | null;
        };
        /** WorkoutExerciseSummary */
        WorkoutExerciseSummary: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            exercise_kind: components["schemas"]["ExerciseKind"];
            /** Set Count */
            set_count: number;
            /** Best Set Display */
            best_set_display: string;
            /** Estimated 1Rm */
            estimated_1rm?: number | null;
        };
        /** WorkoutSessionCreate */
        WorkoutSessionCreate: {
            /** Template Id */
            template_id?: string | null;
            /** Planned Workout Id */
            planned_workout_id?: string | null;
            /** Notes */
            notes?: string | null;
            /** Name */
            name?: string | null;
            /** Exercises */
            exercises?: components["schemas"]["WorkoutExerciseItem"][] | null;
        };
        /** WorkoutSessionResponse */
        WorkoutSessionResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Template Id */
            template_id?: string | null;
            /** Planned Workout Id */
            planned_workout_id?: string | null;
            /** Name */
            name?: string | null;
            /** Started At */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /** Notes */
            notes?: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["WorkoutExerciseItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** WorkoutSessionUpdate */
        WorkoutSessionUpdate: {
            /** Exercises */
            exercises?: components["schemas"]["WorkoutExerciseItem"][] | null;
            /** Notes */
            notes?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Name */
            name?: string | null;
            /**
             * Skipped
             * @description Whether the workout was skipped
             */
            skipped?: boolean | null;
        };
        /** WorkoutSetItem */
        WorkoutSetItem: {
            /** @default normal */
            set_type: components["schemas"]["SetType"];
            /** Completed At */
            completed_at?: string | null;
            /**
             * Completed
             * @default false
             */
            completed: boolean | null;
            /** Reps */
            reps?: number | null;
            /** Weight */
            weight?: number | null;
            /** Distance */
            distance?: number | null;
            /** Duration */
            duration?: number | null;
            /** Calories */
            calories?: number | null;
            /** Rest Timer */
            rest_timer?: number | null;
            /**
             * Is Volume Pr
             * @default false
             */
            is_volume_pr: boolean;
            /**
             * Is Weight Pr
             * @default false
             */
            is_weight_pr: boolean;
            /**
             * Is Reps Pr
             * @default false
             */
            is_reps_pr: boolean;
            /**
             * Is Duration Pr
             * @default false
             */
            is_duration_pr: boolean;
        };
        /** WorkoutSummary */
        WorkoutSummary: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Duration Seconds
             * @default 0
             */
            duration_seconds: number;
            /**
             * Exercise Count
             * @default 0
             */
            exercise_count: number;
            /**
             * Set Count
             * @default 0
             */
            set_count: number;
            /**
             * Total Volume Kg
             * @default 0
             */
            total_volume_kg: number;
            /**
             * Pr Count
             * @default 0
             */
            pr_count: number;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["WorkoutExerciseSummary"][];
            /** Template Id */
            template_id?: string | null;
        };
        /** WorkoutTemplateCreate */
        WorkoutTemplateCreate: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["TemplateExerciseItem"][];
        };
        /** WorkoutTemplateResponse */
        WorkoutTemplateResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["TemplateExerciseItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apple_signin_api_auth_apple_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversations_api_ai_conversations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_job_api_ai_conversations__conversation_id__active_job_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ai_chat_api_ai_chat_start_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_api_ai_conversations__conversation_id__messages_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_context_api_profile_context_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_insights_api_profile_insights_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercises_api_exercises_get: {
        parameters: {
            query?: {
                body_part?: string | null;
                exercise_kind?: components["schemas"]["ExerciseKind"] | null;
                search?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_exercises_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exercise_api_exercises__exercise_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_exercise_api_exercises__exercise_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                exercise_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_templates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutTemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workouts_api_workouts_get: {
        parameters: {
            query?: {
                limit?: number;
                start?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_workout_api_workouts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_api_workouts__workout_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_api_workouts__workout_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_api_workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_count_all_api_workouts_count_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutCountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_history_by_exercise_api_workouts_history_by_exercise_get: {
        parameters: {
            query: {
                exercise_id: string;
                days_back?: number;
                limit_workouts?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workouts_by_date_api_workouts_by_date_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD in user's local date */
                date: string;
                /** @description User timezone offset in minutes, e.g. Israel winter=120, summer=180 */
                tz_offset_minutes?: number;
                /** @description If false, only workouts with ended_at != None */
                include_incomplete?: boolean;
                limit?: number;
                start?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workouts_by_date_range_api_workouts_by_date_range_get: {
        parameters: {
            query: {
                /** @description YYYY-MM-DD (local) */
                start_date: string;
                /** @description YYYY-MM-DD (local), inclusive */
                end_date: string;
                /** @description User timezone offset in minutes */
                tz_offset_minutes?: number;
                /** @description If false, only workouts with ended_at != None */
                include_incomplete?: boolean;
                limit?: number;
                start?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workouts_batch_api_workouts_batch__workout_ids__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_detail_api_workouts__workout_id__detail_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prs_api_prs_get: {
        parameters: {
            query?: {
                exercise_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PRRecordResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planned_workouts_api_planned_workouts_get: {
        parameters: {
            query?: {
                start_date?: string | null;
                end_date?: string | null;
                date?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_planned_workout_api_planned_workouts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedWorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planned_workout_api_planned_workouts__workout_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_planned_workout_api_planned_workouts__workout_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedWorkoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedWorkoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_planned_workout_api_planned_workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                workout_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_api__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
